### ISSUE TITLE
Some saves can't be loaded, as clicking on them and pressing Enter while highlighted does nothing

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#370] opened 2017-03-20 07:21 UTC
These autosaves, except the 3000 BC save, can't be loaded.  Highlighting them and pressing enter or clicking on them does nothing.

http://lex.clansfx.co.uk/requested/CivOnesomeunloadablesaves.zip

**Comment by SWY1985** [comment] 2017-03-20 14:50
This is part of #153 and #248. Load/Save games are currently not working correctly, but this will be resolved soon.

**Comment by AlexFolland** [comment] 2017-03-20 15:00
I thought this was a separate issue because it seemed to be a UI issue, unrelated to whether the engine can load save data passed to it.

**Comment by SWY1985** [comment] 2017-03-21 08:56
The invalid saves are caused by destroyed cities crashing the save game process. This has been fixed in the next commit.

**Comment by SWY1985** [comment] 2017-03-21 08:57
The original game attempts to load these games anyway, but I don't think that's a good idea.
At a later time, I may add an error message when trying to load an invalid save game.

**Closed** 2017-03-21 08:56 UTC
