### ISSUE TITLE
Researching learned technology continues after finding a hut (scrolls of wisdom) that teaches it

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#260] opened 2017-03-01 19:58 UTC
Notice how in this screenshot, I've already learned Code of Laws, but it's still being researched.  This happened previously with Alphabet also.  Notice how there are 2 entries for Alphabet.

![image](https://cloud.githubusercontent.com/assets/601517/23478413/28a69af2-fe76-11e6-91d3-96681aecd2e4.png)

**Comment by SWY1985** [comment] 2017-03-02 14:48
I could not reproduce this. I made a fix a couple of days ago, so this should no longer happen. May I ask which version of CivOne you are using?

**Comment by AlexFolland** [comment] 2017-03-02 16:33
I am currently using 0.1.0pre-alpha1-r715 (the prebuilt Windows exe), as when I build in VS Code using the instructions here, https://github.com/SWY1985/CivOne/wiki/How-to-build-and-run-on-Windows%3F, only a DLL is produced and I couldn't figure out how to run it without debugging, which doesn't work on Windows.  I would gladly test using the latest if I knew how.  I am mostly familiar with building other projects, but this one stumped me.  Sorry for the outdated bug report then!

**Comment by SWY1985** [comment] 2017-03-03 06:10
You still managed to find a number of open bugs, even in the older version. I'm sorry for not updating the build instructions (will do that in a couple of days) and posting an old version on the website. In the forum thread on CivFanatics, you can find the latest version (0.1.0pre-alpha1-r888): https://forums.civfanatics.com/threads/civone-an-open-source-remake-of-civilization-1.535036/page-18

I will also update the website with the latest version, immediately. Sorry!

**Comment by AlexFolland** [comment] 2017-03-03 06:20
I love Civilization, and have always come back to it throughout my life.  I don't like any version of Civilization after the second one (so, 3 onward), as I think they convoluted the gameplay to the point of annoyance.  Civ 1 is relaxing and Civ 2 is good in the right mood.  I appreciate your reimplementation more than I can express; especially the attention to accuracy.  I have a few more minor issues I could report, but they are so obvious that I am assuming you know about them and plan to fix them when the more important features are implemented, and I don't want to hassle you.

Feel free to close this issue.

**Comment by SWY1985** [comment] 2017-03-03 06:37
I too love this game, and still play it regularly. I was hoping someone would make a project like mine for many years, until I just decided to start working on it myself. I'm happy (and a bit amazed) that I've already come this far.
Comments like yours make me want to continue work on CivOne even more, so I really appreciate it. Thank you so much!

No worries, all bug reports, even the obvious ones, are appreciated. Please do report any issue you might find, it's very helpful. I'd rather close an issue that is already solved, than miss an obvious bug in the final release.

I have updated the build instructions, if you have time, could you please see if they work for you?
https://github.com/SWY1985/CivOne/wiki/How-to-build-and-run-on-Windows%3F

I will close this issue now.

**Closed by SWY1985** 2017-03-03 06:37 UTC
Labels: bug, question
