### ISSUE TITLE
Discovering ancient wisdom in a hut should show the wisdom

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#95] opened 2016-09-11 16:58 UTC
And if the wisdom is something you are currently researching, it should let you choose the next wisdom.

**Comment by SWY1985** [comment] 2016-09-11 19:25
You're not seeing a civilopedia page because the ancient scrolls of wisdom are not implemented yet.
That is a known issue. Duplicate of #31 .

**Closed by SWY1985** 2016-09-11 19:25 UTC
Labels: duplicate
