### ISSUE TITLE
Saving crashes game

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#372] opened 2017-03-21 18:06 UTC
Autosave or manual save crashes Civone.

**Comment by SWY1985** [comment] 2017-03-22 05:55
I cannot reproduce this. Do you get some kind of error message? Do you get it all the time, or have you discovered something, changed tax/luxury/science rate, attacked some city or had one of your cities taken, anything special?

**Comment by kazgaroth011** [comment] 2017-03-22 06:12
Nope, just regularly played the game. I had to turn off autosave because it always crashed at 3000 BC. Regular saves also. I did about 4 playthroughs and it always crashed. I get a message which you usually get when a program stops responding. I'll write what exactly happens when I get back home.

**Comment by SWY1985** [comment] 2017-03-22 06:14
Thanks you.

**Comment by kazgaroth011** [comment] 2017-03-22 16:37
So, here's a screenshot. Immediately after I press enter I get this:

![clipboard02](https://cloud.githubusercontent.com/assets/21365802/24209273/19aec342-0f26-11e7-9a86-05e4fc01aea8.png)

**Comment by SWY1985** [comment] 2017-03-23 05:47
Unfortunately, the actual error message is further to the top in the console window. This gives me an idea what could go wrong, but I still don't know what's happening.

**Comment by kazgaroth011** [comment] 2017-03-23 05:51
OK, I'll try to paste whole message here.

**Comment by SWY1985** [comment] 2017-03-23 05:52
Could you send me all your save files, I think one of the may be corrupt and that's causing this message.

**Comment by SWY1985** [comment] 2017-03-23 05:54
You can mail me at: stefan@civone.com

**Comment by SWY1985** [comment] 2017-03-23 06:01
I have made adjustments to the code to detect corrupt save files and show an appropriate message. It deviates from the original game, which will attempt to load a game no matter what. But I feel this is an improvement to the original game and I hope it fixes the game crash upon saving.

I will build a new preview later today so you can test it.

**Comment by SWY1985** [comment] 2017-03-23 06:52
Possibly related to #343

**Comment by SWY1985** [comment] 2017-03-23 10:57
Can you test the new build?

**Comment by kazgaroth011** [comment] 2017-03-23 16:13
It works now, you can close it !

**Comment by SWY1985** [comment] 2017-03-23 17:51
Thank you, I'm glad it worked :-)

**Comment by kazgaroth011** [comment] 2017-03-23 21:24
OK, so the game crashed again when I tried to save.
Played another game and when I tried saving I saw this:
![clipboard02](https://cloud.githubusercontent.com/assets/21365802/24270933/5e64e8c6-1017-11e7-8234-52bebfe85096.png)

The message of incorrect size appears on the first place, where I tried saving previous game.

**Comment by SWY1985** [comment] 2017-03-24 06:13
Yes, I've implemented two messages:
- Incorrect file size
- Incorrect header

Once I get save games fully working, it shouldn't happen anymore, but for now it's a good identifier to what's wrong.
Please, can you email any corrupt/incorrect save files to me? My email address is: stefan@civone.com
Thank you.

**Comment by kazgaroth011** [comment] 2017-03-24 08:56
I'll try if it happens again. I overwrote the last corrupted save with a new one.

**Comment by kazgaroth011** [comment] 2017-03-24 15:00
I emailed you one file that caused a crash when saving.

**Comment by SWY1985** [comment] 2017-08-29 12:12
This issue appears to have been solved. The rest of the save game issues will be fixed in #248.

**Closed by SWY1985** 2017-08-29 12:12 UTC
Labels: bug, question
