### ISSUE TITLE
Cancel a fortify order by bringing up a window

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#138] opened 2016-09-15 18:04 UTC
As seen from the below screenshot.
Pressing the window should cancel the order.
Pressing away from the order should do nothing (and the unit will be fortified in the next turn).

![clipboard02](https://cloud.githubusercontent.com/assets/21365802/18561229/4dcd5db8-7b7f-11e6-9280-f239387ae4c7.png)

**Comment by SWY1985** [comment] 2016-09-15 19:06
Duplicate of #70

**Closed by SWY1985** 2016-09-15 19:06 UTC
Labels: duplicate
