### ISSUE TITLE
Which version of Civilization will CivOne target?

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#319] opened 2017-03-09 19:47 UTC
In trying to figure out why one of my Civilization folders has 3-contented Temples and the other has 2, I read on CivFanatics that there are several versions of Civilization for DOS.

The thread listed versions 475.01, 475.02, 475.03, 475.04, and 475.05.  I have one that they didn't list.

Here is the first screen in CIV.EXE from my "CIV" folder:

![image](https://cloud.githubusercontent.com/assets/601517/23767296/f85a0d00-04bc-11e7-8382-6deff2808227.png)

Here is the first screen in CIV.EXE from my "CIV1ULTI" folder:

![image](https://cloud.githubusercontent.com/assets/601517/23767310/0903cf74-04bd-11e7-8469-9ee88b99961e.png)

I don't remember exactly where I got this "CIV1ULTI" folder from, but I do remember that I got it a long long time ago in order to play without a game-breaking bug that happens inevitably late in the game in Civilization version 475.01, and I was hoping that this version fixed it.

From what it says on this screen, it seems this is a private in-office MPS version, but I'm not sure.  I wonder if version 475.05, the last version apparently known, also has Temples relieving 3 unhappy citizens, and also has whatever bug fixes this "Version 475.01/1.301 [with] Temporary Revisions By Stan Oliver" contains.  I could not find a copy of 475.05 to test with, unfortunately.

Anyway, the point of this ticket is to try to clarify which version of Civilization that CivOne will intend to target in the end, in terms of game mechanics, which may be different across versions.

**Comment by SWY1985** [comment] 2017-03-09 19:55
Personally, I have version 474.01 (the floppy version) which is the same as 475.01.
Later versions had several bug fixes and changes to the game. Most notably, attempts to fix the advisor bug... after version x.01, the Shift 5+6 cheat was disabled.
I will primarily target version 474.01, and add features from later versions where needed. For example: I have already added the Rename City feature which was introduced in version x.04 (I think).

There's altered versions of Civilization floating around on the internet with changed rules. You may have one of those. I will no deviate from the original game, but if there were official changes to the game, I will try to add optional patches that can be enabled/disabled.

**Comment by AlexFolland** [comment] 2017-03-09 20:17
The biggest problem in 475.01 is when you have all the technologies and you build a new city, you the production change menu in that city bugs out and shows nothing but a "MORE" button which makes it repeat the same small bugged window.  CivOne already doesn't have that problem, and simply goes to 3 pages.  That is the most important fix the unknown version I have has, aside from the Temple difference.  It will take more research to determine if 3 unhappy citizens being contented is an official change or not.  Googling "Stan Oliver" along with "Civilization", "Civ1", "Civ", etc. doesn't return useful results, so I'm having trouble there.  I'll check the Windows version.

![image](https://cloud.githubusercontent.com/assets/601517/23768784/f9cfc134-04c1-11e7-9880-75d79b1ed78b.png)
![image](https://cloud.githubusercontent.com/assets/601517/23768854/34647844-04c2-11e7-8a77-2acbcae556ea.png)

It seems the Windows version 1.2.0 from 1993 also has Temples making 2 unhappy citizens content.  That is probably the official rule then.

**Comment by AlexFolland** [comment] 2017-03-09 20:21
Come to think of it, in terms of game rules, the Windows version is probably the best official resource, as it is quite polished in that way.

**Comment by SWY1985** [comment] 2017-03-09 20:30
If I know the differences between the different versions (DOS, x.1/2/3/4/5, Windows, Mac, Amiga), I can create patches so everyone can choose their own preferences.

I will probably add non-official patches too, like being able to play with only 2 Civs and enabling Deity and Deity+ difficulty levels.

**Comment by kazgaroth011** [comment] 2017-03-09 20:55
regarding this topic here are the differences between the versions:
https://www.civfanatics.com/civ1/faq/section-a-general-information/#gen1

**Comment by AlexFolland** [comment] 2017-03-09 20:56
Does CivNet factor in here?  I know CivNet has "Smart Settlers", which I remember being a nice feature which made the settlers automate supposedly optimal irrigation and roads, though I was not a very advanced player at that time, so I didn't know how to min/max.  For the record, it also says that Temple converts 2 unhappy citizens:

![image](https://cloud.githubusercontent.com/assets/601517/23770407/c67641fe-04c7-11e7-948e-980a3b683c06.png)

**Comment by kazgaroth011** [comment] 2017-03-09 21:05
Are there any differences between CivNet and DOS versions? I always preferred the DOS version and never liked the new graphics of CivNEt.

**Comment by AlexFolland** [comment] 2017-03-09 21:13
The differences seem to be mostly convenient features and cosmetics.  There is the "Smart Settlers" setting for Settlers units that I mentioned earlier.  There is what is effectively a city production queue, and an automated production system in cities.

![image](https://cloud.githubusercontent.com/assets/601517/23770797/5ce000d4-04c9-11e7-858e-12978d85cf99.png)

The user interface is quite polished, also.  You can zoom in and out to see tiles at the size you wish.  There is a convenient city list pop-out menu.  And of course, the main bonus feature is the multiplayer mode which supports setting either traditional ordered turns or simultaneous turns.

I don't see any differences in any game rules.  It seems like a highly polished but rules-unchanged version of Civilization, with its main selling point being the addition of networked multiplayer.

**Comment by kazgaroth011** [comment] 2017-03-09 21:41
Hmm it's nice and all but I would still just stick to reproducing DOS version, since most people use it.
These enhancements could probably be available with mods.

**Comment by AlexFolland** [comment] 2017-03-09 21:43
I agree.  Reproducing the DOS version but without the bugs listed in https://www.civfanatics.com/civ1/faq/section-a-general-information/ is an excellent goal.

**Comment by SWY1985** [comment] 2017-03-10 06:05
Thanks for that list, good reference.
In the next version, I'm going to implement the Barracks maintenance costs (increasing twice in the original game). I will make an optional patch to disable free Barracks, as was done in 47x.3

I've not yet implemented (un)happiness, but does anyone know what 'very unhappy citizens' do?

**Comment by AlexFolland** [comment] 2017-03-10 06:38
Here are some discussions involving "very unhappy citizens":

https://forums.civfanatics.com/threads/very-unhappy-people.50455/
https://forums.civfanatics.com/threads/expanding-at-emperor-difficulty-v474-03.370237/

There's not much information here, but there are screenshots of what the very unhappy citizens look like.  They look exactly like unhappy citizens, but with red clothes instead of black.  I need to test the patches to glean more information about them, but I honestly can't find them.

**Comment by SWY1985** [comment] 2017-08-29 14:32
I'm going to close this issue, thanks for the input.
CivOne will be a recreation of Civilization for DOS 474.01, with obvious bugs fixed, and optional additional features from later patches.

Convienent features that were added in the Windows/Mac/CivNET games will have to be recreated as plugins.

Very unhappy citizens may get added in a later version, but they will be optional.

**Closed by SWY1985** 2017-08-29 14:32 UTC
Labels: question
