### ISSUE TITLE
Numpad enter key doesn't work

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#277] opened 2017-03-03 11:57 UTC
Pressing the numpad enter key should perform the same functions as the standard enter key, but currently doesn't.

**Comment by SWY1985** [comment] 2017-03-03 12:44
It does work on my computer. Can you provide some details? What is your keyboard locale for example? Doesn't it work anywhere or is there a specific screen where it doesn't work?

**Comment by AlexFolland** [comment] 2017-03-03 19:05
I'm using US-Dvorak, but testing with US (qwerty) exhibits the same issue.

Here are some examples of when numpad enter key doesn't work but the main enter key does.

![image](https://cloud.githubusercontent.com/assets/601517/23564779/3601018e-0000-11e7-82e2-da359ad1d5ac.png)

![image](https://cloud.githubusercontent.com/assets/601517/23564945/909eaf88-0000-11e7-9646-8d3ee943a5ca.png)

![image](https://cloud.githubusercontent.com/assets/601517/23565039/e97469b8-0000-11e7-9918-a6af553c4789.png)

![image](https://cloud.githubusercontent.com/assets/601517/23565058/fad0122a-0000-11e7-90b9-55c878947931.png)

Actually, I guess I should stop posting more screenshots, as it doesn't seem to work anywhere.

For the record, it does work in Civilization in DOSBox.

**Comment by SWY1985** [comment] 2017-03-03 22:07
I have tested on a Linux machine and the Numpad Enter doesn't work either. The problem is probably not with your computer, I will attempt to fix it.

**Comment by AlexFolland** [comment] 2017-03-04 02:53
It's OpenTK's OpenTK.Input.Key.KeypadEnter that is somehow wrong.  It's set to 82 and the other enter key (OpenTK.Input.Key.Enter) is 49.

I'm not sure what to change to solve this, but updating OpenTK might work.  It seems CivOne is using an old version of it.  I couldn't figure out how to update it though.  I managed to build OpenTK myself and had an OpenTK.dll, but it didn't work when I swapped it with C:\Users\Alex\.nuget\packages\OpenTK.NETCore\1.1.2571.6431\lib\netstandard1.3\OpenTK.dll.  I tried pursuing a different approach, but the project.json stuff was completely beyond me.

**Comment by SWY1985** [comment] 2017-03-04 07:54
The thing is, I switched from Mono to .NET Core because .NET Core is faster and it allows semi-standalone compilation. But .NET Core is still sort of a preview (just like CivOne). In a month or two, .NET Core 2.0 and .NET Standard 2.0 will be released, which will be a lot more mature, and OpenTK will be updated to the .NET Standard 2.0 soon after. Until then we'll have to do with this older version of OpenTK.
Not too much of a problem, I'm pretty sure I can get it to work for one simple reason: I want it to.

Expect a bugfix for this issue soon.

**Comment by SWY1985** [comment] 2017-03-04 09:03
The key just registers as an unknown keypress, no logical way to identify the key.
I'm not out of ideas yet, but the solution won't be easy.

**Comment by AlexFolland** [comment] 2017-03-04 22:45
That all makes sense!  I admire your explanation and decision.  That key is so nice to use when moving with the numpad is so useful in CivOne.

**Comment by SWY1985** [comment] 2017-03-05 20:37
I have come to believe that Numpad Enter is the only key on my keyboard that registers as an unknown button, so I've made Key.Unkonwn function as Enter key. This solves the problem for now.

**Closed** 2017-03-05 20:38 UTC
Labels: bug, question
