### ISSUE TITLE
No buildings or roads in city view

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#367] opened 2017-03-17 22:25 UTC
I noticed this while it was showing the Barracks-building animation, so I checked city view for the screenshot.

![image](https://cloud.githubusercontent.com/assets/601517/24065106/e8b632a6-0b25-11e7-9570-8e0b1486ccc2.png)

As an aside, it's hilarious how Verona is 1 dude who lives alone in a barbed-wire-fenced building.

**Comment by SWY1985** [comment] 2017-03-18 08:16
This happens because the map generation algorithm is not perfect. I consider this a duplicate of #32, which is not yet completed.

**Closed by SWY1985** 2017-03-18 08:16 UTC
Labels: duplicate
